{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load necessary packages\n",
    "import pandas as pd\n",
    "import plotly.express as px        # high-level plotly module\n",
    "import plotly.graph_objects as go  # lower-level plotly module with more functions\n",
    "import pandas_datareader as pdr    # we are grabbing the data and wb functions from the package\n",
    "import datetime as dt              # for time and date\n",
    "import requests                    # api module\n",
    "#from ipywidgets import widgets     # interactive graphs\n",
    "\n",
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output, State\n",
    "import plotly.io as pio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "today = dt.datetime.now().strftime('%B %d, %Y')  # today's date. this will be useful when sourcing results "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Download successful\n"
     ]
    }
   ],
   "source": [
    "url = 'https://api.covidtracking.com/v1/states/daily.json'\n",
    "    \n",
    "response = requests.get(url)\n",
    "\n",
    "if response.status_code == 200: \n",
    "    print('Download successful')\n",
    "    covid = pd.read_json(response.text)  # convert to dataframe\n",
    "elif response.status_code == 301: \n",
    "    print('The server redirected to a different endpoint.')\n",
    "elif response.status_code == 401: \n",
    "    print('Bad request.')\n",
    "elif response.status_code == 401: \n",
    "    print('Authentication required.')\n",
    "elif response.status_code == 403: \n",
    "    print('Access denied.')\n",
    "elif response.status_code == 404: \n",
    "    print('Resource not found')\n",
    "else: \n",
    "    print('Server busy')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>state</th>\n",
       "      <th>positive</th>\n",
       "      <th>probableCases</th>\n",
       "      <th>negative</th>\n",
       "      <th>pending</th>\n",
       "      <th>totalTestResultsSource</th>\n",
       "      <th>totalTestResults</th>\n",
       "      <th>hospitalizedCurrently</th>\n",
       "      <th>hospitalizedCumulative</th>\n",
       "      <th>...</th>\n",
       "      <th>hospitalizedIncrease</th>\n",
       "      <th>hash</th>\n",
       "      <th>commercialScore</th>\n",
       "      <th>negativeRegularScore</th>\n",
       "      <th>negativeScore</th>\n",
       "      <th>positiveScore</th>\n",
       "      <th>score</th>\n",
       "      <th>grade</th>\n",
       "      <th>pos_rate</th>\n",
       "      <th>month</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2020-10-25</td>\n",
       "      <td>AK</td>\n",
       "      <td>14064.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>545905.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>totalTestsViral</td>\n",
       "      <td>559969.0</td>\n",
       "      <td>58.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>175a4f70a15c098ac277246bff6ae33838f66029</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td></td>\n",
       "      <td>NaN</td>\n",
       "      <td>October 2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2020-10-25</td>\n",
       "      <td>AL</td>\n",
       "      <td>184355.0</td>\n",
       "      <td>26474.0</td>\n",
       "      <td>1144785.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>totalTestsViral</td>\n",
       "      <td>1302666.0</td>\n",
       "      <td>922.0</td>\n",
       "      <td>19595.0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>14421edcbba78df1217731644f92a3a03211c44d</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td></td>\n",
       "      <td>NaN</td>\n",
       "      <td>October 2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020-10-25</td>\n",
       "      <td>AR</td>\n",
       "      <td>106115.0</td>\n",
       "      <td>7235.0</td>\n",
       "      <td>1189120.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>totalTestsViral</td>\n",
       "      <td>1288000.0</td>\n",
       "      <td>618.0</td>\n",
       "      <td>6718.0</td>\n",
       "      <td>...</td>\n",
       "      <td>11</td>\n",
       "      <td>813725c51fabd6f6078ad953d35346c5d5987dc1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td></td>\n",
       "      <td>NaN</td>\n",
       "      <td>October 2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2020-10-25</td>\n",
       "      <td>AS</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1616.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>totalTestsViral</td>\n",
       "      <td>1616.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>3c89978d48f3a4f830660f7149129437b5808f1e</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td></td>\n",
       "      <td>NaN</td>\n",
       "      <td>October 2020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020-10-25</td>\n",
       "      <td>AZ</td>\n",
       "      <td>238163.0</td>\n",
       "      <td>5462.0</td>\n",
       "      <td>1473706.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>totalTestsPeopleViral</td>\n",
       "      <td>1706407.0</td>\n",
       "      <td>828.0</td>\n",
       "      <td>21086.0</td>\n",
       "      <td>...</td>\n",
       "      <td>43</td>\n",
       "      <td>7b19d3005937c11aaefe84f6c137e0ae59da6655</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td></td>\n",
       "      <td>NaN</td>\n",
       "      <td>October 2020</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 57 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        date state  positive  probableCases   negative  pending  \\\n",
       "0 2020-10-25    AK   14064.0            NaN   545905.0      NaN   \n",
       "1 2020-10-25    AL  184355.0        26474.0  1144785.0      NaN   \n",
       "2 2020-10-25    AR  106115.0         7235.0  1189120.0      NaN   \n",
       "3 2020-10-25    AS       0.0            NaN     1616.0      NaN   \n",
       "4 2020-10-25    AZ  238163.0         5462.0  1473706.0      NaN   \n",
       "\n",
       "  totalTestResultsSource  totalTestResults  hospitalizedCurrently  \\\n",
       "0        totalTestsViral          559969.0                   58.0   \n",
       "1        totalTestsViral         1302666.0                  922.0   \n",
       "2        totalTestsViral         1288000.0                  618.0   \n",
       "3        totalTestsViral            1616.0                    NaN   \n",
       "4  totalTestsPeopleViral         1706407.0                  828.0   \n",
       "\n",
       "   hospitalizedCumulative  ...  hospitalizedIncrease  \\\n",
       "0                     NaN  ...                     0   \n",
       "1                 19595.0  ...                     0   \n",
       "2                  6718.0  ...                    11   \n",
       "3                     NaN  ...                     0   \n",
       "4                 21086.0  ...                    43   \n",
       "\n",
       "                                       hash  commercialScore  \\\n",
       "0  175a4f70a15c098ac277246bff6ae33838f66029                0   \n",
       "1  14421edcbba78df1217731644f92a3a03211c44d                0   \n",
       "2  813725c51fabd6f6078ad953d35346c5d5987dc1                0   \n",
       "3  3c89978d48f3a4f830660f7149129437b5808f1e                0   \n",
       "4  7b19d3005937c11aaefe84f6c137e0ae59da6655                0   \n",
       "\n",
       "   negativeRegularScore  negativeScore positiveScore score grade pos_rate  \\\n",
       "0                     0              0             0     0            NaN   \n",
       "1                     0              0             0     0            NaN   \n",
       "2                     0              0             0     0            NaN   \n",
       "3                     0              0             0     0            NaN   \n",
       "4                     0              0             0     0            NaN   \n",
       "\n",
       "          month  \n",
       "0  October 2020  \n",
       "1  October 2020  \n",
       "2  October 2020  \n",
       "3  October 2020  \n",
       "4  October 2020  \n",
       "\n",
       "[5 rows x 57 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "covid['pos_rate'] = 100*(covid['positiveTestsViral']+covid['positiveTestsAntigen'])/(covid['totalTestsPeopleViral']+ covid['totalTestsAntigen'])\n",
    "covid['date'] = pd.to_datetime(covid['date'], format='%Y%m%d')\n",
    "covid['month'] = covid['date'].dt.strftime('%B %Y') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "covid.drop(covid[covid['state'] == \"AS\"].index, inplace=True)         # Drop American Samoa\n",
    "covid.drop(covid[covid['date'] < '2020-03-01'].index, inplace=True)   # Drop January and February when there are few cases\n",
    "\n",
    "months = covid['month'].unique().tolist()\n",
    "months.reverse()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Prepare for Dash\n",
    "df = covid[['date','state','positive','hospitalizedCurrently','deathIncrease','death']]\n",
    "df2 = df.copy()\n",
    "df2.state = 'All States'\n",
    "df = df.append(df2, ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "app = dash.Dash()\n",
    "\n",
    "header = html.H1(children=\"United States Covid-19 Trends (as of \" + today + \")\")\n",
    "\n",
    "markdown_text = '''\n",
    "### Dash and Markdown\n",
    "The following graphs depict select Covid-19 trends by state. \n",
    "Use the filters to choose a subset of states and/or dates to sharpen the analysis. \n",
    "Source: The Atlantic [Covid-19 Tracking Project](https://covidtracking.com)\n",
    "'''\n",
    "markdown = dcc.Markdown(children=markdown_text)\n",
    "\n",
    "# Dropdown\n",
    "dropdown =  html.P([\n",
    "            html.Label(\"Select States\"),\n",
    "            dcc.Dropdown(\n",
    "            id='state-dropdown',\n",
    "            options=[{'label': i, 'value': i} for i in df['state'].unique().tolist()],\n",
    "            multi=True,\n",
    "            searchable= True)\n",
    "            ], style = {'width' : '80%',\n",
    "                        'fontSize' : '20px',\n",
    "                        'padding-left' : '100px',\n",
    "                        'display': 'inline-block'})\n",
    "    \n",
    "# range slider\n",
    "slider =    html.P([\n",
    "            html.Label(\"Select Months\"),\n",
    "            dcc.RangeSlider(id = 'slider',\n",
    "                        marks = {i : months[i] for i in range(0, len(months))},\n",
    "                        min = 0,\n",
    "                        max = len(months)-1,\n",
    "                        value = [0, len(months)-1])\n",
    "            ], style = {'width' : '80%',\n",
    "                        'fontSize' : '20px',\n",
    "                        'padding-left' : '100px',\n",
    "                        'display': 'inline-block'})\n",
    "    \n",
    "graph1 = dcc.Graph(id=\"positive\", style={'display': 'inline-block'})\n",
    "graph2 = dcc.Graph(id=\"curhospital\", style={'display': 'inline-block'})\n",
    "graph3 = dcc.Graph(id=\"newdeaths\", style={'display': 'inline-block'})\n",
    "graph4 = dcc.Graph(id=\"totdeaths\", style={'display': 'inline-block'})\n",
    "\n",
    "row1 = html.Div(children=[graph1, graph2])\n",
    "row2 = html.Div(children=[graph3, graph4])\n",
    "\n",
    "layout = html.Div(children=[header, markdown, dropdown, slider, row1, row2], style={\"text-align\": \"center\"})\n",
    "app.layout = layout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output('positive', 'figure'),\n",
    "    [Input('state-dropdown', 'value')],\n",
    "    [Input('slider', 'value')])\n",
    "    \n",
    "# STEP 5: Update Figure\n",
    "def update_figure(state_values,month_values):\n",
    "\n",
    "    if state_values is None:\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='positive')        \n",
    "    elif state_values[0]==\"All States\":\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='positive')\n",
    "    else:\n",
    "        if not isinstance(state_values, list): state_values = [state_values]\n",
    "        temp = df.loc[df['state'].isin(state_values)]\n",
    "        dff = temp.pivot(index='date',columns='state',values='positive')\n",
    "    \n",
    "    # Filter by months\n",
    "    dff = dff[(dff.index >= dt.datetime.strptime(months[month_values[0]],\"%B %Y\")) & (dff.index <= dt.datetime.strptime(months[month_values[1]],\"%B %Y\"))]\n",
    "    \n",
    "    fig = go.Figure()\n",
    "    for column in dff.columns.to_list():\n",
    "        fig.add_trace(\n",
    "            go.Scatter(\n",
    "                x = dff.index,\n",
    "                y = dff[column],\n",
    "                name = column,\n",
    "                mode='lines',\n",
    "                opacity=0.8,\n",
    "                hovertemplate = '<extra></extra>State: ' + column + '<br>Date: ' + dff.index.strftime('%m/%d') +'<br>Value: %{y:,}'\n",
    "            )\n",
    "        )\n",
    "      \n",
    "    # Update remaining layout properties\n",
    "    fig.update_layout(\n",
    "        title={\n",
    "                'text': \"New Cases\",\n",
    "                'x':0.5,'xanchor': 'center',\n",
    "                'font':{'size': 18}\n",
    "                },\n",
    "        hovermode='closest',plot_bgcolor='rgba(0,0,0,0)',\n",
    "        hoverlabel=dict(\n",
    "            bgcolor = 'white',\n",
    "            font_size=16),\n",
    "        width=700,   \n",
    "        xaxis=dict(\n",
    "            title=\"Date\",\n",
    "            zeroline=True,\n",
    "            showgrid=False,  # Removes X-axis grid lines \n",
    "            ),\n",
    "        yaxis=dict(\n",
    "            zeroline=True, \n",
    "            showgrid=False  # Removes Y-axis grid lines\n",
    "            )\n",
    "    )\n",
    "        \n",
    "    fig.update_xaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    fig.update_yaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output('curhospital', 'figure'),\n",
    "    [Input('state-dropdown', 'value')],\n",
    "    [Input('slider', 'value')])\n",
    "    \n",
    "# STEP 5: Update Figure\n",
    "def update_figure(state_values,month_values):\n",
    "\n",
    "    if state_values is None:\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='hospitalizedCurrently')        \n",
    "    elif state_values[0]==\"All States\":\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='hospitalizedCurrently')\n",
    "    else:\n",
    "        if not isinstance(state_values, list): state_values = [state_values]\n",
    "        temp = df.loc[df['state'].isin(state_values)]\n",
    "        dff = temp.pivot(index='date',columns='state',values='hospitalizedCurrently')\n",
    "    \n",
    "    # Filter by months\n",
    "    dff = dff[(dff.index >= dt.datetime.strptime(months[month_values[0]],\"%B %Y\")) & (dff.index <= dt.datetime.strptime(months[month_values[1]],\"%B %Y\"))]\n",
    "    \n",
    "    fig = go.Figure()\n",
    "    for column in dff.columns.to_list():\n",
    "        fig.add_trace(\n",
    "            go.Scatter(\n",
    "                x = dff.index,\n",
    "                y = dff[column],\n",
    "                name = column,\n",
    "                mode='lines',\n",
    "                opacity=0.8,\n",
    "                hovertemplate = '<extra></extra>State: ' + column + '<br>Date: ' + dff.index.strftime('%m/%d') +'<br>Value: %{y:,}'\n",
    "            )\n",
    "        )\n",
    "      \n",
    "    # Update remaining layout properties\n",
    "    fig.update_layout(\n",
    "        title={\n",
    "                'text': \"Current Hospitalizations\",\n",
    "                'x':0.5,'xanchor': 'center',\n",
    "                'font':{'size': 18}\n",
    "                },\n",
    "        hovermode='closest',plot_bgcolor='rgba(0,0,0,0)',\n",
    "        hoverlabel=dict(\n",
    "            bgcolor = 'white',\n",
    "            font_size=16),\n",
    "        width=700,  \n",
    "        xaxis=dict(\n",
    "            title=\"Date\",\n",
    "            zeroline=True,\n",
    "            showgrid=False,  # Removes X-axis grid lines \n",
    "            ),\n",
    "        yaxis=dict(\n",
    "            zeroline=True, \n",
    "            showgrid=False  # Removes Y-axis grid lines\n",
    "            )\n",
    "    )\n",
    "        \n",
    "    fig.update_xaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    fig.update_yaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output('newdeaths', 'figure'),\n",
    "    [Input('state-dropdown', 'value')],\n",
    "    [Input('slider', 'value')])\n",
    "    \n",
    "# STEP 5: Update Figure\n",
    "def update_figure(state_values,month_values):\n",
    "\n",
    "    if state_values is None:\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='deathIncrease')        \n",
    "    elif state_values[0]==\"All States\":\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='deathIncrease')\n",
    "    else:\n",
    "        if not isinstance(state_values, list): state_values = [state_values]\n",
    "        temp = df.loc[df['state'].isin(state_values)]\n",
    "        dff = temp.pivot(index='date',columns='state',values='deathIncrease')\n",
    "    \n",
    "    # Filter by months\n",
    "    dff = dff[(dff.index >= dt.datetime.strptime(months[month_values[0]],\"%B %Y\")) & (dff.index <= dt.datetime.strptime(months[month_values[1]],\"%B %Y\"))]\n",
    "    \n",
    "    fig = go.Figure()\n",
    "    for column in dff.columns.to_list():\n",
    "        fig.add_trace(\n",
    "            go.Scatter(\n",
    "                x = dff.index,\n",
    "                y = dff[column],\n",
    "                name = column,\n",
    "                mode='lines',\n",
    "                opacity=0.8,\n",
    "                hovertemplate = '<extra></extra>State: ' + column + '<br>Date: ' + dff.index.strftime('%m/%d') +'<br>Value: %{y:,}'\n",
    "            )\n",
    "        )\n",
    "      \n",
    "    # Update remaining layout properties\n",
    "    fig.update_layout(\n",
    "        title={\n",
    "                'text': \"Daily Deaths\",\n",
    "                'x':0.5,'xanchor': 'center',\n",
    "                'font':{'size': 18}\n",
    "                },\n",
    "        hovermode='closest',plot_bgcolor='rgba(0,0,0,0)',\n",
    "        hoverlabel=dict(\n",
    "            bgcolor = 'white',\n",
    "            font_size=16),\n",
    "        width=700,  \n",
    "        xaxis=dict(\n",
    "            title=\"Date\",\n",
    "            zeroline=True,\n",
    "            showgrid=False,  # Removes X-axis grid lines \n",
    "            ),\n",
    "        yaxis=dict(\n",
    "            zeroline=True, \n",
    "            showgrid=False  # Removes Y-axis grid lines\n",
    "            )\n",
    "    )\n",
    "        \n",
    "    fig.update_xaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    fig.update_yaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output('totdeaths', 'figure'),\n",
    "    [Input('state-dropdown', 'value')],\n",
    "    [Input('slider', 'value')])\n",
    "    \n",
    "# STEP 5: Update Figure\n",
    "def update_figure(state_values,month_values):\n",
    "\n",
    "    if state_values is None:\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='death')        \n",
    "    elif state_values[0]==\"All States\":\n",
    "        dff = df.copy()\n",
    "        dff.drop(dff[dff['state'] == \"All States\"].index, inplace=True)\n",
    "        dff = dff.pivot(index='date',columns='state',values='death')\n",
    "    else:\n",
    "        if not isinstance(state_values, list): state_values = [state_values]\n",
    "        temp = df.loc[df['state'].isin(state_values)]\n",
    "        dff = temp.pivot(index='date',columns='state',values='death')\n",
    "    \n",
    "    # Filter by months\n",
    "    dff = dff[(dff.index >= dt.datetime.strptime(months[month_values[0]],\"%B %Y\")) & (dff.index <= dt.datetime.strptime(months[month_values[1]],\"%B %Y\"))]\n",
    "    \n",
    "    fig = go.Figure()\n",
    "    for column in dff.columns.to_list():\n",
    "        fig.add_trace(\n",
    "            go.Scatter(\n",
    "                x = dff.index,\n",
    "                y = dff[column],\n",
    "                name = column,\n",
    "                mode='lines',\n",
    "                opacity=0.8,\n",
    "                hovertemplate = '<extra></extra>State: ' + column + '<br>Date: ' + dff.index.strftime('%m/%d') +'<br>Value: %{y:,}'\n",
    "            )\n",
    "        )\n",
    "      \n",
    "    # Update remaining layout properties\n",
    "    fig.update_layout(\n",
    "        title={\n",
    "                'text': \"Total Deaths\",\n",
    "                'x':0.5,'xanchor': 'center',\n",
    "                'font':{'size': 18}\n",
    "                },\n",
    "        hovermode='closest',plot_bgcolor='rgba(0,0,0,0)',\n",
    "        hoverlabel=dict(\n",
    "            bgcolor = 'white',\n",
    "            font_size=16),\n",
    "        width=700,  \n",
    "        xaxis=dict(\n",
    "            title=\"Date\",\n",
    "            zeroline=True,\n",
    "            showgrid=False,  # Removes X-axis grid lines \n",
    "            ),\n",
    "        yaxis=dict(\n",
    "            zeroline=True, \n",
    "            showgrid=False  # Removes Y-axis grid lines\n",
    "            ),\n",
    "    )\n",
    "        \n",
    "    fig.update_xaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    fig.update_yaxes(showline=True, linewidth=2, linecolor='black')\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: on\n"
     ]
    }
   ],
   "source": [
    "app.run_server(debug=True, use_reloader=False)  # Turn off reloader if inside Jupyter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
